### ISSUE TITLE
Question about DQFD result

### ISSUE THREAD

**Issue by kimbring2** [minerllabs/baselines#16]
Hello,

I am trying to reenact a DQFD for MineRLTreechop-v0 task. by running a dqfd.bash file. I change a pretrain step parameter to 250000, 500000 because of traning time is little long. After pretraning, my agent looks only at the continuation sky, not the tree. 

Can you tell me if anything about that issue?

**Comment by jmlouw** [comment]
I tried retraining the PPO agent, but couldn't reproduce their results. After 350 episodes, the agent still gets an average score of 13. Any ideas?

**Comment by marioyc** [comment]
Hello, did you change any other parameters besides the number of pretraining steps?

I haven't really tried tuning the number of pretraining steps, just kept the number they used on the paper, but seeing how the losses evolved during pretraining I wouldn't expect the results of 500000 to be too different compared to the ones with 750000 pretraining steps.

![MineRLTreechop-v0_pretraining](https://user-images.githubusercontent.com/382898/68734507-ea1feb00-061d-11ea-852c-343e6c8a46bd.png)

**Comment by marioyc** [comment]
Also, for both DQfD and PPO, notice that the results were obtained on version 0.2.3, quite a few changes have been made leading to the latest 0.2.9 version.

**Comment by kimbring2** [comment]
@marioyc In my case, I only changed pretraining step parameter. I think it looks good idea trying in 0.2.3 version.

Thank you for your replying!!

**Comment by MadcowD** [comment]
Just so you know, there are some important fixes that 0.2.9 brings, and using 0.2.3  shpuld be avoided

**Comment by kimbring2** [comment]
@MadcowD Yes, you are right. When I test it on 0.2.3 version. There was error after doing 750000 pretrain. I really want to know how they implement DQFD and Action Branching Architectures together. It is reason of why I try to reproduce a result.

**Comment by marioyc** [comment]
could you give more details on the error?

**Comment by kimbring2** [comment]
@marioyc I could not capture it. But I can remember it was related with obs['pov']. Looks like a format difference of observation tuple.

**Comment by marioyc** [comment]
I guess you're using the latest published data, updates on the data may also cause such errors, since the data that was used when publishing the baselines may have some differences.

To provide further help I'd need to have more details on the error.

**Comment by Zhouqianqian** [comment]
Hi, I have also run into this problem, I am wondering why the performance of DQFD is worse than that of Rainbow? Empirically DQFD should be better than Rainbow since it have learned some expert policy at the beginning.

**Comment by kimbring2** [comment]
@Zhouqianqian I can not tell the reason properly becasue there is no performance video of DQFD.
