### ISSUE TITLE
ResetTrimInfoWrapper no longer needed

### ISSUE THREAD

**Issue by ashishgaurav13** [minerllabs/baselines#6]
With minerl-0.2.3, `env.reset()` only returns `obs`, so `ResetTrimInfoWrapper` is no longer needed. It should be either commented out or deleted?

The baseline code is using this wrapper for PPO/Rainbow and other implementations.

**Comment by MadcowD** [comment]
Would you be willing to make a PR on this?

**Comment by ashishgaurav13** [comment]
Sure, I can do that. Sorry only had the chance to see this now

**Comment by ashishgaurav13** [comment]
Closing this.
